### ISSUE TITLE
Broken under Leiningen >=2.7.0

### ISSUE THREAD

**Issue by bcarrell** [technomancy/lein-licenses#5]
[leiningen.core.classpath/get-dependencies](https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/classpath.clj#L413) changed arities, so [this line](https://github.com/technomancy/lein-licenses/blob/master/src/leiningen/licenses.clj#L164) is throwing an arity exception.

**Comment by arr-ee** [comment]
I just pushed 0.2.1 (that includes your fix) to clojars.

Thanks!
