### ISSUE TITLE
Emit SPDX-normalised license identifiers

### ISSUE THREAD

**Issue by pmonks** [technomancy/lein-licenses#7]
It would be awesome if lein-license were to emit [SPDX](https://spdx.org/) normalised license identifiers, in addition to the raw text of the license.  Right now the same license can be represented in the output in different ways, making downstream processing more difficult.

**Comment by arr-ee** [comment]
https://github.com/technomancy/lein-licenses#license-name-normalisation was built for this exact reason. You are more than welcome to contribute a list of SPDX synonyms.
